name: Kotlin Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kotlin-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: Check changes
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files_ignore: frontend/**
      - if: github.event_name == 'push' || steps.changed-files.outputs.any_changed == 'true'
        name: Setup Eclipse Temurin 25
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: 25
      - if: github.event_name == 'push' || steps.changed-files.outputs.any_changed == 'true'
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic
      - if: github.event_name == 'push' || steps.changed-files.outputs.any_changed == 'true'
        name: Build & Test
        working-directory: backend
        run: ./gradlew build
